"""pygb — the single Python client API for driving a gbforge ROM.

All scriptable automation (scenarios, checkpoint recipes, detectors)
goes through this package. It speaks one line protocol
(harness/PROTOCOL.md) over a transport:

  StdioTransport — the headless gbctl binary: deterministic, no
                   window, CI-safe. Emulation is parked, so the same
                   script produces the same frames on every machine.

Symbol addresses come exclusively from pygb.symbols (generated by
scripts/gen_symbols.py from the ROM's .noi — run
`make -C harness symbols`). No raw RAM address may be hand-typed in
code that imports this package: a hardcoded address survives a
relink that moves the variable, and then silently asserts on
whatever moved into its place.

Typical use:

    from pygb import GB

    gb = GB.launch_headless()       # spawn gbctl on the retail ROM
    gb.run_frames(600)              # boot + title
    gb.tap("START")
    print(gb.read_sym("score"))
    gb.screenshot("output/title.png")
"""

from .client import GB  # noqa: F401
