#!/usr/bin/env python3
"""Parse SDCC/GBDK .noi and .map files to emit game symbol tables.

Usage:
    python3 gen_symbols.py <game.noi> <output.h> [--py <symbols.py>] [--json <symbols.json>]

Emits up to three artifacts from the same parse:
  <output.h>     C header with ADDR_* defines for the curated WANTED_SYMBOLS
                 list (back-compat for harness scenario .c files)
  --py PATH      Python module with ALL symbols (RAM dict + banked-ROM dict)
                 for harness/pygb consumers — no hand-typed addresses anywhere
  --json PATH    Same data as JSON for non-Python consumers (fork server,
                 Swift editor apps)

The single-source-of-truth rule: no raw RAM address may appear outside
these generated artifacts. Regenerated by `make -C harness symbols`
whenever the ROM's .noi changes.

The .noi file (primary) has full symbol names:
    DEF _board 0xC0B1

Banked ROM symbols encode the bank in the high bits (0xBBAAAA):
    DEF _sfx_play 0x144188   -> bank 0x14, address 0x4188

The .map file (fallback) has truncated names in columns:
    0000C0B1  _board    |    0000C82E  _cpu_know |    ...

We prefer .noi because .map truncates names to ~9 chars.
If a .map path is given, we also try the sibling .noi file.
"""

import hashlib
import json
import re
import sys
import os

# Symbols to extract: game_symbol -> (C_define, comment)
WANTED_SYMBOLS = {
    "_board":              ("ADDR_BOARD",              "uint8_t[64] — 8x8 board grid"),
    "_cursor_x":           ("ADDR_CURSOR_X",           "uint8_t — cursor X position"),
    "_cursor_y":           ("ADDR_CURSOR_Y",           "uint8_t — cursor Y position"),
    "_tile_selected":      ("ADDR_TILE_SELECTED",      "uint8_t — tile grab state"),
    "_processing_matches": ("ADDR_PROCESSING_MATCHES", "uint8_t — cascade in progress"),
    "_score":              ("ADDR_SCORE",              "uint16_t — score (LE)"),
    "_moves_left":         ("ADDR_MOVES_LEFT",         "uint8_t — moves remaining"),
    "_debug_req":          ("ADDR_DEBUG_REQ",          "uint8_t — debug mailbox request (dev ROM)"),
}

# RAM address range for the Game Boy (WRAM: 0xC000–0xDFFF, HRAM: 0xFF80–0xFFFE)
# We only want data symbols in RAM, not ROM code addresses.
RAM_RANGES = [(0xC000, 0xE000), (0xFF80, 0xFFFF)]


def addr_is_ram(addr):
    """Check if an address is in Game Boy RAM."""
    for lo, hi in RAM_RANGES:
        if lo <= addr < hi:
            return True
    return False


def parse_noi_file(path, banked=None):
    """Parse .noi file: 'DEF symbol_name 0xADDR' lines.

    Returns 16-bit symbols; if `banked` (a dict) is given, ROM symbols
    with a bank encoded in the high bits (raw > 0xFFFF) are collected
    there as name -> (bank, addr).
    """
    symbols = {}
    with open(path, "r") as f:
        for line in f:
            m = re.match(r"DEF\s+(\S+)\s+0x([0-9A-Fa-f]+)", line.strip())
            if m:
                name = m.group(1)
                addr = int(m.group(2), 16)
                if addr <= 0xFFFF:
                    symbols[name] = addr
                elif banked is not None:
                    banked[name] = (addr >> 16, addr & 0xFFFF)
    return symbols


def parse_map_file(path):
    """Parse .map file (column-based, truncated names)."""
    symbols = {}
    with open(path, "r") as f:
        for line in f:
            # Match "  HHHHHHHH  symbol_name" entries separated by |
            for entry in line.split("|"):
                entry = entry.strip()
                m = re.match(r"([0-9A-Fa-f]{8})\s+(\S+)", entry)
                if m:
                    addr = int(m.group(1), 16)
                    name = m.group(2)
                    if addr <= 0xFFFF:
                        symbols[name] = addr
    return symbols


def emit_header(symbols, output_path):
    """Write C header with symbol address defines."""
    found = []
    missing = []

    for sym_name, (define_name, comment) in sorted(WANTED_SYMBOLS.items()):
        if sym_name in symbols:
            addr = symbols[sym_name]
            found.append((define_name, addr, comment))
        else:
            missing.append(sym_name)

    with open(output_path, "w") as f:
        f.write("/* Auto-generated by gen_symbols.py — do not edit */\n")
        f.write("#ifndef GBF_SYMBOLS_H\n")
        f.write("#define GBF_SYMBOLS_H\n\n")

        for define_name, addr, comment in found:
            f.write(f"#define {define_name:30s} 0x{addr:04X}  /* {comment} */\n")

        if missing:
            f.write(f"\n/* Symbols not found ({len(missing)}):\n")
            for m in missing:
                f.write(f"   {m}\n")
            f.write("*/\n")

        f.write("\n#endif /* GBF_SYMBOLS_H */\n")

    print(f"gen_symbols: {len(found)} symbols resolved, "
          f"{len(missing)} missing → {output_path}")


def classify(symbols, banked):
    """Split raw symbol tables into the shapes the .py/.json artifacts use.

    Only SDCC C-object symbols (leading underscore) are kept; linker
    section markers (s__CODE_5, l__DATA, .__.ABS.) are noise. The
    leading underscore is stripped so consumers use C-source names.
    """
    ram = {}
    home = {}
    for name, addr in symbols.items():
        if not name.startswith("_") or name.startswith("__"):
            continue
        if addr_is_ram(addr):
            ram[name[1:]] = addr
        else:
            home[name[1:]] = addr
    rom = {name[1:]: {"bank": bank, "addr": addr}
           for name, (bank, addr) in banked.items()
           if name.startswith("_") and not name.startswith("__")}
    return ram, home, rom


def rom_sha1_for(noi_path):
    """SHA1 of the .gbc sibling of the .noi, for staleness checks."""
    gbc = os.path.splitext(noi_path)[0] + ".gbc"
    if not os.path.exists(gbc):
        return None
    h = hashlib.sha1()
    with open(gbc, "rb") as f:
        h.update(f.read())
    return h.hexdigest()


def emit_python(ram, home, rom, rom_sha1, output_path):
    """Write the pygb symbols module. Deterministic: sorted, no timestamps."""
    with open(output_path, "w") as f:
        f.write('"""Auto-generated by gen_symbols.py — do not edit.\n\n')
        f.write("Symbol addresses extracted from the ROM's .noi file.\n")
        f.write("Regenerate with: make -C harness symbols\n")
        f.write('"""\n\n')
        f.write(f"ROM_SHA1 = {rom_sha1!r}\n\n")
        f.write("# WRAM/HRAM data symbols: name -> address\n")
        f.write("RAM = {\n")
        for name in sorted(ram):
            f.write(f"    {name!r}: 0x{ram[name]:04X},\n")
        f.write("}\n\n")
        f.write("# HOME-bank (non-banked ROM) symbols: name -> address\n")
        f.write("HOME = {\n")
        for name in sorted(home):
            f.write(f"    {name!r}: 0x{home[name]:04X},\n")
        f.write("}\n\n")
        f.write("# Banked ROM symbols: name -> (bank, address)\n")
        f.write("BANKED = {\n")
        for name in sorted(rom):
            f.write(f"    {name!r}: (0x{rom[name]['bank']:02X}, "
                    f"0x{rom[name]['addr']:04X}),\n")
        f.write("}\n\n\n")
        f.write("def addr(name):\n")
        f.write('    """Address of a RAM data symbol by its C-source name."""\n')
        f.write("    return RAM[name]\n")
    print(f"gen_symbols: {len(ram)} RAM + {len(home)} HOME + "
          f"{len(rom)} banked symbols → {output_path}")


def emit_json(ram, home, rom, rom_sha1, output_path):
    """Write the JSON artifact for non-Python consumers."""
    payload = {
        "rom_sha1": rom_sha1,
        "ram": {k: ram[k] for k in sorted(ram)},
        "home": {k: home[k] for k in sorted(home)},
        "banked": {k: rom[k] for k in sorted(rom)},
    }
    with open(output_path, "w") as f:
        json.dump(payload, f, indent=1)
        f.write("\n")
    print(f"gen_symbols: JSON → {output_path}")


def main():
    args = sys.argv[1:]
    py_path = json_path = None
    if "--py" in args:
        i = args.index("--py")
        py_path = args[i + 1]
        del args[i:i + 2]
    if "--json" in args:
        i = args.index("--json")
        json_path = args[i + 1]
        del args[i:i + 2]
    if len(args) != 2:
        print(f"Usage: {sys.argv[0]} <noi_or_map_file> <output.h> "
              f"[--py <symbols.py>] [--json <symbols.json>]",
              file=sys.stderr)
        sys.exit(1)

    input_path = args[0]
    output_path = args[1]

    if not os.path.exists(input_path):
        print(f"gen_symbols: file not found: {input_path}", file=sys.stderr)
        print(f"gen_symbols: build the ROM first: cd examples/cascadia && make",
              file=sys.stderr)
        sys.exit(1)

    symbols = {}
    banked = {}

    # Try .noi first (full names), then .map (truncated names)
    base, ext = os.path.splitext(input_path)
    noi_path = base + ".noi"
    map_path = base + ".map"

    noi_symbols = {}
    if ext == ".noi" or os.path.exists(noi_path):
        path = noi_path if ext != ".noi" else input_path
        if os.path.exists(path):
            noi_symbols = parse_noi_file(path, banked)
            symbols = dict(noi_symbols)
            print(f"gen_symbols: parsed {len(symbols)} symbols from {path}")

    # Supplement with .map if available
    if ext == ".map" or os.path.exists(map_path):
        path = map_path if ext != ".map" else input_path
        if os.path.exists(path):
            map_syms = parse_map_file(path)
            # Only add symbols not already found (prefer .noi full names)
            added = 0
            for name, addr in map_syms.items():
                if name not in symbols:
                    symbols[name] = addr
                    added += 1
            if added:
                print(f"gen_symbols: added {added} symbols from {path}")

    if not symbols:
        print("gen_symbols: no symbols parsed!", file=sys.stderr)
        sys.exit(1)

    emit_header(symbols, output_path)

    if py_path or json_path:
        # Only full-name .noi symbols go into the py/json tables — the
        # .map fallback's ~9-char truncated names would add unusable
        # duplicates (e.g. 'active_e' next to 'active_effects').
        ram, home, rom = classify(noi_symbols or symbols, banked)
        sha1 = rom_sha1_for(noi_path if os.path.exists(noi_path) else input_path)
        if py_path:
            emit_python(ram, home, rom, sha1, py_path)
        if json_path:
            emit_json(ram, home, rom, sha1, json_path)


if __name__ == "__main__":
    main()
