#ifndef GBFORGE_ABILITY_H_INCLUDED
#define GBFORGE_ABILITY_H_INCLUDED

/* gbforge runtime — the ability interpreter. One machinery for
 * legacy spells and any future game's weapons: cost + targeting +
 * filter + effect opcode, all table data (generated by
 * gen_abilities from the Ability definitions). */

#include <stdint.h>

#include "engine.h"

#ifdef __SDCC
#include <asm/types.h>
#else
#ifndef BANKED
#define BANKED
#endif
#endif

/* targeting */
#define AB_TARGET_NONE      0
#define AB_TARGET_TILE      1
#define AB_TARGET_SWAP_PAIR 2

/* target filters */
#define AB_FILTER_ANY_NONEMPTY     0
#define AB_FILTER_MANNA            1
#define AB_FILTER_METAL_PROMOTABLE 2
#define AB_FILTER_NONE             3

/* effect opcodes */
#define AB_OP_DESTROY_TILE  0
#define AB_OP_DESTROY_ROW   1
#define AB_OP_DESTROY_TYPE  2
#define AB_OP_CONVERT_TILE  3
#define AB_OP_PROMOTE_TILE  4
#define AB_OP_SHUFFLE_MANNA 5
#define AB_OP_FREE_SWAP     6

typedef struct {
    uint8_t cost_fire, cost_water, cost_earth;
    uint8_t targeting;
    uint8_t target_filter;
    uint8_t op;
    uint8_t op_arg;
    uint16_t unlock_cost;   /* knowledge price in the store */
    uint8_t cast_sfx;       /* SFX id on cast (0xFF = theme default) */
} ng_ability;

/* Enough manna in the engine pools? */
uint8_t ab_can_cast(const ng_ability *a, const rt_engine *e) BANKED;

/* Valid target under the ability's filter? (untargeted: always 1) */
uint8_t ab_target_ok(const ng_ability *a, const rt_engine *e,
                     uint8_t tx, uint8_t ty) BANKED;

/* Deduct cost and apply the effect opcode to the board. Returns 1 on
 * success (0 = cost/target rejected; nothing changed). FREE_SWAP
 * deducts cost only — the caller performs the swap. */
uint8_t ab_cast(const ng_ability *a, rt_engine *e,
                uint8_t tx, uint8_t ty) BANKED;

#endif
