#ifndef GBFORGE_ANIM_H_INCLUDED
#define GBFORGE_ANIM_H_INCLUDED

/* gbforge runtime — resolution-script playback at data-driven timing.
 *
 * The engine (engine.h) resolves a pass and emits rt_events; this
 * interpreter OWNS THE VISUAL BOARD and advances it by those events
 * with timing taken from rt_anim_params. Logic never waits on
 * rendering; rendering never mutates logic state — the decoupling the
 * legacy render_gravity_drop() entanglement prevented.
 *
 * Timing lives in a const ROM table (retail) mirrored into WRAM under
 * DEBUG_BUILD, where the animation editor / harness poke it live over
 * the automation socket and replay — the WS3 preview loop. gen_anim.py
 * will emit both from AnimationSpec definitions; the defaults here are
 * the legacy-measured values.
 */

#include <stdint.h>

#include "engine.h"

#ifndef BANKED
#define BANKED
#endif

typedef struct {
    uint8_t flash_hold;        /* match flash, frames (legacy 8)      */
    uint8_t clear_hold;        /* beat after tiles vanish (legacy 6)  */
    uint8_t pass_gap;          /* between cascade passes (legacy 5)   */
    uint8_t gravity_delay[8];  /* frames per fall step (legacy
                                  {3,2,2,1,1,1,1,1}, clamped at [7]) */
    uint8_t swap_frames;       /* slide duration (legacy 12)          */
    uint8_t swap_curve[16];    /* cumulative px offsets, ends at 16   */
    uint8_t shake_frames;      /* shake duration (legacy 7)           */
    int8_t shake_dx[8];        /* per-frame SCX offsets               */
    int8_t shake_dy[8];        /* per-frame SCY offsets               */
    uint8_t sparkle_frames;    /* frames per burst phase (legacy 6)   */
    uint8_t wiggle_steps;      /* hint nudge positions (legacy 6)     */
    uint8_t wiggle_step_frames;/* frames per position (legacy 5)      */
    int8_t wiggle_offsets[8];  /* diagonal px offsets, end at 0       */
} rt_anim_params;

/* Generated by gbforge gen_anim from the AnimationSpec definitions
 * (gen/anim_tables.c). The manifest (gen/anim_manifest.json) maps
 * every field's mirror offset for the animation editor. */
extern const rt_anim_params anim_params_rom;

/* The live parameter block: ROM const in retail, WRAM mirror under
 * DEBUG_BUILD (symbol `anim_params` — poke and replay). */
#ifdef DEBUG_BUILD
extern rt_anim_params anim_params;
#define RTA_PARAMS (&anim_params)
#else
#define RTA_PARAMS (&anim_params_rom)
#endif

/* Initialize playback state: adopt the engine's board as the visual
 * board and (DEBUG) load the WRAM mirror from ROM defaults. */
void rta_init(const uint8_t board[8][8]) BANKED;

/* Set the visual board directly (mode init / debug redraw). */
void rta_sync(const uint8_t board[8][8]) BANKED;

/* Play one resolved pass's event buffer against the visual board:
 * flash matched cells, clear + transmute, animate falls stepwise,
 * reveal refills. Blocks for the animation duration (vsync-paced). */
void rta_play(const rt_engine *e) BANKED;

/* Sprite-based tile slide between two adjacent cells, following the
 * swap curve. On return the visual board and BG show the two tiles
 * exchanged. A failed swap plays it again with the coordinates
 * swapped (the legacy reverse animation). */
/* Install the game's per-frame pump (input + cursor redraw during
   blocking animations — legacy render_delay_with_cursor). */
void rta_set_frame_hook(void (*fn)(void)) BANKED;

void rta_play_swap(uint8_t x1, uint8_t y1,
                   uint8_t x2, uint8_t y2) BANKED;

/* Screen shake: non-blocking SCX/SCY offsets from the shake tables.
 * start arms it; apply advances one frame — called after every vsync
 * (the interpreter's own waits pump it, and the main loop must too). */
void rta_start_shake(void) BANKED;
void rta_apply_shake(void) BANKED;

/* Floating "+N" ticker — pumped by every wait and the main loop. */
void rta_update_floats(void) BANKED;

/* Warning flash: whole board greyed/restored, cycles × hold (the
 * legacy no-moves punish cue: 3 × 10 frames). */
void rta_play_warning(const uint8_t board[8][8]) BANKED;

/* Hint wiggle: the tile at (x,y) jiggles per the wiggle tables,
 * rendered as quadrant sprites over a blanked BG cell. */
void rta_play_wiggle(uint8_t x, uint8_t y) BANKED;

#endif
