#ifndef GBFORGE_FX_H_INCLUDED
#define GBFORGE_FX_H_INCLUDED

/* gbforge runtime — full-screen cast effects.
 *
 * rt_fx_spec rows are generated by gen_abilities from each
 * Ability's CastFx. rtfx_cast() is the whole cast cutscene: show
 * the ability's name overlay (merlin, boxed, over the board), run
 * the effect, and return with scroll + palettes restored — the
 * caller's usual board blit then reveals the ability's result.
 *
 * Raster kinds (wave/shear) busy-poll LY instead of arming an LYC
 * ISR: the cutscene owns the CPU anyway, and HOME stays untouched.
 */

#include <stdint.h>

#ifdef __SDCC
#include <asm/types.h>
#else
#ifndef BANKED
#define BANKED
#endif
#endif

#define RTFX_NONE      0
#define RTFX_FLASH     1  /* a=pulses, b=1 flashes to black        */
#define RTFX_SHAKE     2  /* a=amplitude px, decays                */
#define RTFX_WAVE      3  /* a=amplitude px, b=phase speed         */
#define RTFX_SHEAR     4  /* a=amplitude px, b=split tile row      */
#define RTFX_TINT      5  /* a,b,c = target r,g,b (5-bit)          */
#define RTFX_GRAYFADE  6  /* desaturate toward per-color luma      */

typedef struct {
    uint8_t kind;
    uint8_t frames;
    uint8_t a, b, c;
} rt_fx_spec;

void rtfx_run(const rt_fx_spec *fx) BANKED;

/* Overlay + effect for ability index `idx` (0-based), using the
 * generated ng_ability_fx / ng_ability_ovl tables. Safe to call
 * for abilities with no fx (returns immediately). */
void rtfx_cast(uint8_t idx) BANKED;

#endif
