#ifndef GBFORGE_TITLE_H_INCLUDED
#define GBFORGE_TITLE_H_INCLUDED

/* gbforge runtime — title screen + arrow menu, entirely data-driven
 * (ng_title generated by gen_title from the TitleScreen definition).
 */

#include <stdint.h>

#ifdef __SDCC
#include <asm/types.h>
#else
#ifndef BANKED
#define BANKED
#endif
#endif

typedef struct {
    const uint8_t *tiles;   /* UI-letter tile indices */
    uint8_t n_tiles;        /* baked run width (tiles)          */
    uint8_t value;          /* returned on confirm              */
    uint8_t arrow_x;        /* two tiles left of the label ink
                               (per item: labels are pixel-
                               centered so ink start varies)     */
} ng_menu_item;

typedef struct {
    uint8_t run_x, first_y; /* where the baked runs sit          */
    uint8_t row_step;
    uint8_t count;
    const ng_menu_item *items;
} ng_menu;

typedef struct {
    uint8_t logo_letters;   /* 16x16 letters, 4 tiles each */
    uint8_t logo_x, logo_y;
    uint8_t deco_x, deco_y, deco_n;
    uint8_t deco_attrs[16];
    const uint16_t *palettes;   /* 8x4 RGB555 */
    ng_menu menu;
} ng_title;

/* Show the title screen and run its menu; blocks until confirm.
 * Returns the selected item's value — or 0xFF if a debug-mailbox
 * request arrived (left pending for the caller). */
uint8_t rtt_show(const ng_title *t) BANKED;

#endif
