#ifndef GBFORGE_TITLE_H_INCLUDED
#define GBFORGE_TITLE_H_INCLUDED

/* gbforge runtime — title screen + arrow menu, entirely data-driven
 * (ng_title generated by gen_title from the TitleScreen definition).
 */

#include <stdint.h>

#ifdef __SDCC
#include <asm/types.h>
#else
#ifndef BANKED
#define BANKED
#endif
#endif

typedef struct {
    const uint8_t *tiles;   /* baked 2bpp label run              */
    uint8_t n_tiles;        /* baked run width (tiles)           */
    uint8_t run_x;          /* per item: the arrow is tile-aligned
                               but the ink is placed at pixel
                               precision, so each row's run can
                               start in a different tile          */
    uint8_t value;          /* returned on confirm               */
    uint8_t arrow_x;        /* tile holding the arrow; arrow, gap
                               and label are centred as one unit  */
} ng_menu_item;

typedef struct {
    uint8_t first_y;
    uint8_t row_step;
    uint8_t count;
    const ng_menu_item *items;
} ng_menu;

typedef struct {
    /* Baked 16x16-face logo: a run of `logo_tiles` columns, two tile
       rows tall, row-major (all of row 0, then all of row 1). */
    const uint8_t *logo;
    uint8_t logo_tiles;
    uint8_t logo_x, logo_y;
    uint8_t deco_x, deco_y, deco_n;
    uint8_t deco_attrs[16];
    const uint16_t *palettes;   /* 8x4 RGB555 */
    ng_menu menu;
} ng_title;

/* Show the title screen and run its menu; blocks until confirm.
 * Returns the selected item's value — or 0xFF if a debug-mailbox
 * request arrived (left pending for the caller). */
uint8_t rtt_show(const ng_title *t) BANKED;

#endif
