#ifndef GBFORGE_UI_CORE_H_INCLUDED
#define GBFORGE_UI_CORE_H_INCLUDED

/* gbforge runtime — boxed-overlay primitives.
 *
 * An ng_overlay is pure data (generated by gen_ui from the Overlay
 * definitions): box geometry + chrome tiles + palette + text lines.
 * This collapses the legacy pattern of six hand-drawn goal/result
 * overlays whose geometry differences were bug-fix scar tissue.
 */

#include <stdint.h>

#ifdef __SDCC
#include <asm/types.h>
#else
#ifndef BANKED
#define BANKED
#endif
#endif

typedef struct {
    uint8_t x, y, w, h;
    uint8_t pal;
    uint8_t t_top, t_bot, t_left, t_right;
    uint8_t c_tl, c_tr, c_bl, c_br;
    uint8_t fill;
} ng_box_style;

typedef struct {
    uint8_t dy;          /* row within the box            */
    const char *text;    /* centered in the box interior  */
} ng_overlay_line;

typedef struct {
    ng_box_style box;
    const ng_overlay_line *lines;
    uint8_t line_count;
} ng_overlay;

/* Draw the box chrome + fill. */
void ui_box(const ng_box_style *s) BANKED;

/* Draw the full overlay: box + centered tile-font text lines. */
void ui_show_overlay(const ng_overlay *o) BANKED;

#endif
