#ifndef GBFORGE_UI_CORE_H_INCLUDED
#define GBFORGE_UI_CORE_H_INCLUDED

/* gbforge runtime — boxed-overlay primitives.
 *
 * An ng_overlay is pure data (generated by gen_ui from the Overlay
 * definitions): box geometry + chrome tiles + palette + text lines.
 * This collapses the legacy pattern of six hand-drawn goal/result
 * overlays whose geometry differences were bug-fix scar tissue.
 */

#include <stdint.h>

#ifdef __SDCC
#include <asm/types.h>
#else
#ifndef BANKED
#define BANKED
#endif
#endif

typedef struct {
    uint8_t x, y, w, h;
    uint8_t pal;
    uint8_t t_top, t_bot, t_left, t_right;
    uint8_t c_tl, c_tr, c_bl, c_br;
    uint8_t fill;
} ng_box_style;

typedef struct {
    uint8_t dy;          /* row within the box                     */
    uint8_t dx;          /* first interior column of the span      */
    const uint8_t *tiles;/* baked 2bpp span: text composed, pixel-
                            centered horizontally AND vertically at
                            BUILD time (lines straddle tile rows;
                            empty rows/columns are trimmed)        */
    uint8_t n_tiles;     /* span width in tiles                    */
} ng_overlay_line;

typedef struct {
    ng_box_style box;
    const ng_overlay_line *lines;
    uint8_t line_count;
    uint8_t icon_tile;   /* leading tile before line 0 (cast icon) */
    uint8_t icon_pal;
    uint8_t icon_dx;     /* interior column */
    uint8_t icon_dy;     /* interior row (line 0's row)            */
    uint8_t has_icon;
} ng_overlay;

/* Draw the box chrome + fill. */
void ui_box(const ng_box_style *s) BANKED;

/* Draw the full overlay: box + VWF text lines (merlin font). */
void ui_show_overlay(const ng_overlay *o) BANKED;

#endif
