"""Emit overlay definitions (gen/ui_overlays.{h,c}).

Border tiles and palettes are emitted as the SYMBOLIC C macros from
the editor-owned res headers (UI_TILE_*, PAL_*) — the C compiler
resolves them, so sprite-editor re-exports can never desynchronize
the generated UI.

Text lines are BAKED: each line is composed against the res VWF
font at build time, centered at pixel granularity inside the box
interior (glyphs freely straddle tile boundaries), shadowed, and
emitted as ready-to-upload 2bpp tile data. The runtime just uploads
tiles — no VWF at overlay-show time, and centering is exact.
"""

import os
import re


class MerlinFont:
    """recode + widths + 1bpp glyph bitmaps from res/merlin_font.c."""

    def __init__(self, recode, widths, bitmaps):
        self.recode = recode
        self.widths = widths
        self.bitmaps = bitmaps  # list of 8-row 1bpp glyphs

    @classmethod
    def load(cls, out_dir):
        """Load the font from the res pack next to the output dir.

        generated/ and res/ are siblings inside a game directory, so
        the font travels with the art it was designed against — a
        re-skin that changes the font changes the baked overlays on
        the next `make gen`, with no codegen edit."""
        path = os.path.join(out_dir, "..", "res", "merlin_font.c")
        if not os.path.exists(path):
            return None
        src = open(path).read()

        def table(name, sized=True):
            pat = (name + r"\[\d*\]\s*=\s*\{(.*?)\};") if sized else name
            m = re.search(pat, src, re.S)
            if not m:
                return None
            body = re.sub(r"//[^\n]*|/\*.*?\*/", "", m.group(1),
                          flags=re.S)
            return [int(t, 0) for t in
                    re.findall(r"0[xX][0-9a-fA-F]+|\b\d+\b", body)]

        recode = table("merlin_recode")
        widths = table("merlin_widths")
        bitmaps = table("merlin_bitmaps")
        if not recode or not widths or not bitmaps:
            return None
        glyphs = [bitmaps[i * 8:(i + 1) * 8]
                  for i in range(len(bitmaps) // 8)]
        return cls(recode, widths, glyphs)

    def width_px(self, text):
        return sum(self.widths[self.recode[ord(c)]]
                   for c in text if ord(c) < 128)

    def bake_line_at(self, text, tiles, ink_off_px):
        """Bake with the ink starting at ink_off_px inside the run
        (for layouts where the caller solved the position)."""
        return self._bake(text, tiles, ink_off_px)

    def bake_line(self, text, interior_tiles):
        """Compose `text` pixel-centered into interior_tiles 8x8
        tiles. Returns flat 2bpp bytes (16 per tile): text pixels are
        color 3, the +1/+1 drop shadow color 1 — the same look the
        runtime VWF shadow mode produced, but continuous across tile
        boundaries."""
        return self._bake(text, interior_tiles,
                          (interior_tiles * 8 - self.width_px(text)) // 2)

    def _bake(self, text, interior_tiles, start_px):
        width_px = interior_tiles * 8
        rows = [[0] * width_px for _ in range(8)]
        x = start_px
        for c in text:
            g = self.recode[ord(c)] if ord(c) < 128 else 0
            w = self.widths[g]
            bmp = self.bitmaps[g]
            for ry in range(8):
                bits = bmp[ry]
                for rx in range(8):
                    if bits & (0x80 >> rx) and 0 <= x + rx < width_px:
                        rows[ry][x + rx] = 1
            x += w
        # drop shadow: text offset (+1, +1), only where no text
        shadow = [[0] * width_px for _ in range(8)]
        for ry in range(1, 8):
            for rx in range(1, width_px):
                if rows[ry - 1][rx - 1] and not rows[ry][rx]:
                    shadow[ry][rx] = 1
        out = []
        for t in range(interior_tiles):
            for ry in range(8):
                lo = hi = 0
                for rx in range(8):
                    px = t * 8 + rx
                    if rows[ry][px]:
                        lo |= 0x80 >> rx   # color 3: both planes
                        hi |= 0x80 >> rx
                    elif shadow[ry][px]:
                        lo |= 0x80 >> rx   # color 1: lo only
                out += [lo, hi]
        return out


HEADER = """\
/* Auto-generated by gbforge (gen_ui) — do not edit. */
#ifndef GEN_UI_OVERLAYS_H_INCLUDED
#define GEN_UI_OVERLAYS_H_INCLUDED

#include "ui_core.h"

{externs}
#endif
"""

SOURCE = """\
/* Auto-generated by gbforge (gen_ui) — do not edit.
 *
 * Overlay text is baked: pixel-centered against the res VWF font at
 * build time. Same bank as ui_core.c — it uploads these tiles while
 * this bank is mapped. */
#ifdef __SDCC
#pragma bank 4
#endif

#include "ui_core.h"
#include "ui_overlays.h"

#include "tiles_data.h"
#include "palettes.h"

{bodies}
"""

def _pool_size(out_dir):
    """VWF_POOL_SIZE from the res contract — never duplicated here.

    The overlay baker must fail the BUILD when a spec asks for more
    text tiles than the pool holds; reading the number from the same
    header the runtime compiles against is what keeps that check
    honest across re-skins that move the pool."""
    path = os.path.join(out_dir, "..", "res", "merlin_font.h")
    m = re.search(r"#define\s+VWF_POOL_SIZE\s+(\d+)", open(path).read())
    if not m:
        raise SystemExit(f"gen_ui: no VWF_POOL_SIZE in {path}")
    return int(m.group(1))


def _fmt_bytes(data):
    lines = []
    for i in range(0, len(data), 12):
        lines.append("    " + ", ".join(
            f"0x{b:02X}" for b in data[i:i + 12]) + ",")
    return "\n".join(lines)


def _overlay_body(o, font, pool_size):
    b = o.border
    interior = o.size[0] - 2
    interior_rows = o.size[1] - 2
    interior_h = interior_rows * 8
    n = len(o.lines)

    # vertical layout: text block centered in the box interior.
    # Overlays that host dynamic digit appends (the puzzle cards)
    # keep a 16px tile-aligned pitch so the UI digit tiles line up;
    # everything else gets the tight 12px pitch at pixel precision.
    digit_host = o.name.startswith("puzzle_goal") or \
        o.name.startswith("puzzle_next")
    pitch = 16 if digit_host else 12
    block_h = (n - 1) * pitch + 8
    y_start = max(0, (interior_h - block_h) // 2)
    if digit_host:
        y_start &= ~7               # snap: every line tile-aligned

    # compose all lines into a pixel canvas (per row: tile-column
    # pairs of 2bpp planes)
    canvas = [bytearray(interior * 2) for _ in range(interior_h)]
    line_dy = []
    for k, (_dy, text) in enumerate(o.lines):
        data = font.bake_line(text, interior)
        y = y_start + k * pitch
        line_dy.append(1 + (y >> 3))
        for t in range(interior):
            for r in range(8):
                if y + r >= interior_h:
                    continue
                canvas[y + r][t * 2] |= data[t * 16 + r * 2]
                canvas[y + r][t * 2 + 1] |= data[t * 16 + r * 2 + 1]

    # emit non-empty 8px rows as trimmed spans
    decls = []
    rows = []
    span_id = 0
    total_pool = 0
    for R in range(interior_rows):
        cols = []
        for t in range(interior):
            ink = 0
            for r in range(8):
                ink |= canvas[R * 8 + r][t * 2]
                ink |= canvas[R * 8 + r][t * 2 + 1]
            cols.append(ink)
        if not any(cols):
            continue
        first = next(i for i, v in enumerate(cols) if v)
        last = max(i for i, v in enumerate(cols) if v)
        span = last - first + 1
        total_pool += span
        data = bytearray()
        for t in range(first, last + 1):
            for r in range(8):
                data.append(canvas[R * 8 + r][t * 2])
                data.append(canvas[R * 8 + r][t * 2 + 1])
        arr = f"baked_{o.name}_{span_id}"
        span_id += 1
        decls.append(
            f"static const uint8_t {arr}[{len(data)}] = {{\n"
            f"{_fmt_bytes(bytes(data))}\n}};\n")
        rows.append(f"    {{ {R + 1}, {first}, {arr}, {span} }}")

    if total_pool > pool_size:
        raise SystemExit(
            f"gen_ui: overlay '{o.name}' needs {total_pool} pool "
            f"tiles but the res contract provides {pool_size}")

    # the puzzle number is appended after the PUZZLE line at
    # runtime — export each overlay's line rows for that
    dy_defines = "".join(
        f"#define OVL_{o.name.upper()}_LINE{k}_DY {d}\n"
        for k, d in enumerate(line_dy))

    lines_name = f"lines_{o.name}"
    decls.append(
        f"static const ng_overlay_line {lines_name}[{len(rows)}] = {{\n"
        + ",\n".join(rows) + "\n};\n")
    return dy_defines, (
        "".join(decls)
        + f"const ng_overlay ovl_{o.name} = {{\n"
        f"    {{ {o.pos[0]}, {o.pos[1]}, {o.size[0]}, {o.size[1]},\n"
        f"      {b.c_palette},\n"
        f"      {b.c_tile('top')}, {b.c_tile('bottom')},\n"
        f"      {b.c_tile('left')}, {b.c_tile('right')},\n"
        f"      {b.c_tile('corner_tl')}, {b.c_tile('corner_tr')},\n"
        f"      {b.c_tile('corner_bl')}, {b.c_tile('corner_br')},\n"
        f"      {b.c_tile('fill')} }},\n"
        f"    {lines_name},\n"
        f"    {len(rows)}\n"
        f"}};\n")


def emit(game, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    overlays = getattr(game, "overlays", [])

    font = MerlinFont.load(out_dir)
    if font is None:
        raise SystemExit(
            "gen_ui: res/merlin_font.c not found — baked overlay text "
            "requires the VWF font source")

    for o in overlays:
        avail_px = (o.size[0] - 2) * 8
        for _dy, text in o.lines:
            px = font.width_px(text)
            if px > avail_px:
                raise SystemExit(
                    f"gen_ui: overlay '{o.name}' line '{text}' is "
                    f"{px}px but the box interior is {avail_px}px "
                    f"— widen the box or shorten the text")
        # Overlays are restored by re-blitting the 8x8 board
        # (bg tiles 1..16 on both axes). A box outside that rect
        # strands its border on screen after dismissal.
        x0, y0 = o.pos
        x1, y1 = x0 + o.size[0], y0 + o.size[1]
        if x0 < 1 or y0 < 1 or x1 > 17 or y1 > 17:
            raise SystemExit(
                f"gen_ui: overlay '{o.name}' box ({x0},{y0})-"
                f"({x1 - 1},{y1 - 1}) leaves the restorable board "
                f"rect (1,1)-(16,16)")


    externs = "".join(
        f"extern const ng_overlay ovl_{o.name};\n" for o in overlays)
    pool_size = _pool_size(out_dir)
    parts = [_overlay_body(o, font, pool_size) for o in overlays]
    bodies = "\n".join(b for _d, b in parts)
    externs += "\n" + "".join(d for d, _b in parts)
    with open(os.path.join(out_dir, "ui_overlays.h"), "w") as f:
        f.write(HEADER.format(externs=externs))
    with open(os.path.join(out_dir, "ui_overlays.c"), "w") as f:
        f.write(SOURCE.format(bodies=bodies))

    out = ["ui_overlays.h", "ui_overlays.c"]

    # Standalone baked strings for hand-written screens (dialogue,
    # keyboard...). Baked full-screen-ish (18 tiles) and centered at
    # pixel granularity inside that run; bank 11 = dialogue's, the
    # consumer that uploads them.
    strings = getattr(game, "ui_strings", None)
    if strings:
        hh = ["/* Auto-generated by gbforge (gen_ui) — do not edit. */",
              "#ifndef GEN_UI_STRINGS_H_INCLUDED",
              "#define GEN_UI_STRINGS_H_INCLUDED",
              "", "#include <stdint.h>", ""]
        cc = ["/* Auto-generated by gbforge (gen_ui) — do not edit. */",
              "#ifdef __SDCC",
              "#pragma bank 11   /* dialogue.c is the consumer */",
              "#endif", "",
              '#include "ui_strings.h"', ""]
        W = 18
        for name, text in strings.items():
            px = font.width_px(text)
            if px > W * 8:
                raise SystemExit(
                    f"gen_ui: ui_string '{name}' is {px}px, max {W * 8}")
            data = font.bake_line(text, W)
            up = name.upper()
            hh.append(f"#define UI_STR_{up}_TILES {W}")
            hh.append(f"extern const uint8_t ui_str_{name}[];")
            cc.append(f'/* "{text}" — pixel-centered in {W} tiles */')
            cc.append(f"const uint8_t ui_str_{name}[{len(data)}] = {{")
            cc.append(_fmt_bytes(data))
            cc.append("};")
            cc.append("")
        # Baked counters: a label plus a live digit field, centered
        # as ONE unit. The label is pixel-baked; the digits must be
        # tile-aligned (the game rewrites them), so the generator
        # solves the layout: label ink start, a small gap adjusted
        # until the digit field lands on a tile boundary, and emits
        # the digit column as a #define.
        counters = getattr(game, "ui_counters", None) or {}
        for name, spec in counters.items():
            text, n_digits = spec[0], spec[1]
            # the screen the counter lives on may be scrolled: bg
            # coordinates = screen - signed(SCX)
            scx = spec[2] if len(spec) > 2 else 0
            scx_signed = scx - 256 if scx > 128 else scx
            label_px = font.width_px(text)
            digits_px = n_digits * 8
            up = name.upper()
            # try gaps 3..10 for a tile-aligned digit field with the
            # unit as close to screen-centered as possible
            best = None
            for gap in range(3, 20):   # digit_x moves ~px/2 per step
                unit = label_px + gap + digits_px
                # unit start in BG pixels, screen-centered under scx
                start = (160 - unit) // 2 + scx_signed
                digit_x_px = start + label_px + gap
                if digit_x_px % 8 == 0:
                    off = abs((start - scx_signed + unit / 2) - 80)
                    if best is None or off < best[0]:
                        best = (off, gap, start, digit_x_px)
            assert best, f"ui_counter '{name}': no tile-aligned layout"
            _, gap, start, digit_x_px = best
            # bake the label into a run starting at a tile boundary,
            # with the ink at the exact computed pixel
            run_x = start // 8
            ink_off = start - run_x * 8
            run_tiles = (ink_off + label_px + 7) // 8
            data = font.bake_line_at(text, run_tiles, ink_off)
            hh.append(f"#define UI_CTR_{up}_X {run_x}")
            hh.append(f"#define UI_CTR_{up}_TILES {run_tiles}")
            hh.append(f"#define UI_CTR_{up}_DIGITS_X {digit_x_px // 8}")
            hh.append(f"#define UI_CTR_{up}_DIGITS {n_digits}")
            # screen-pixel positions for sprite rendering (screen =
            # bg - signed SCX)
            hh.append(f"#define UI_CTR_{up}_RUN_PX "
                      f"{run_x * 8 - scx_signed}")
            hh.append(f"#define UI_CTR_{up}_DIGITS_PX "
                      f"{digit_x_px - scx_signed}")
            hh.append(f"extern const uint8_t ui_ctr_{name}[];")
            cc.append(f'/* "{text}" + {n_digits}-digit field, centered'
                      f" as a unit (gap {gap}px) */")
            cc.append(f"const uint8_t ui_ctr_{name}[{len(data)}] = {{")
            cc.append(_fmt_bytes(data))
            cc.append("};")
            cc.append("")

        hh += ["", "#endif", ""]
        with open(os.path.join(out_dir, "ui_strings.h"), "w") as f:
            f.write("\n".join(hh))
        with open(os.path.join(out_dir, "ui_strings.c"), "w") as f:
            f.write("\n".join(cc))
        out += ["ui_strings.h", "ui_strings.c"]
    return out
