"""Emit the quest campaign tables (gen/quest_config.{h,c}).

Dialogue text is bulky, so the .c carries its own bank pragma —
the runtime quest driver lives in the same bank and reads the
strings directly.
"""

import os

QUEST_BANK = 3

HEADER = """\
/* Auto-generated by gbforge (gen_quest) — do not edit. */
#ifndef GEN_QUEST_CONFIG_H_INCLUDED
#define GEN_QUEST_CONFIG_H_INCLUDED

#include <stdint.h>

#define NGQ_PROFESSOR_COUNT {count}
#define NGQ_BANK {bank}

typedef struct {{
    uint8_t target_tile;      /* timed goal + transmute cap */
    uint8_t time_limit_sec;   /* 0 = professor has no timed stage */
    uint16_t battle_target;   /* knowledge goal for the battle exam */
    uint8_t spell_reward;     /* 1-based ability id granted on win */
    uint8_t portrait;         /* portrait sheet slot */
}} ngq_professor;

extern const ngq_professor ngq_professors[NGQ_PROFESSOR_COUNT];
extern const char *const ngq_prof_names[NGQ_PROFESSOR_COUNT];
extern const char *const ngq_prof_title;
/* [professor][10] dialogue pages in legacy DLG_* slot order */
extern const char *const *const ngq_texts[NGQ_PROFESSOR_COUNT];

#endif
"""

SOURCE_TOP = """\
/* Auto-generated by gbforge (gen_quest) — do not edit. */
#pragma bank {bank}

#include "quest_config.h"

"""


def _cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit(game, out_dir):
    quest = getattr(game, "quest", None)
    if quest is None:
        return []
    os.makedirs(out_dir, exist_ok=True)
    profs = quest.professors

    with open(os.path.join(out_dir, "quest_config.h"), "w") as f:
        f.write(HEADER.format(count=len(profs), bank=QUEST_BANK))

    parts = [SOURCE_TOP.format(bank=QUEST_BANK)]
    for i, p in enumerate(profs):
        lines = ",\n".join(f"    {_cstr(t)}" for t in p.dialogue)
        parts.append(
            f"static const char *const ngq_text_{i}[10] = {{\n{lines}\n}};\n\n")
    parts.append("const char *const *const ngq_texts[NGQ_PROFESSOR_COUNT]"
                 " = {\n")
    parts.append(",\n".join(f"    ngq_text_{i}" for i in range(len(profs))))
    parts.append("\n};\n\n")

    parts.append("const char *const ngq_prof_names[NGQ_PROFESSOR_COUNT]"
                 " = {\n")
    parts.append(",\n".join(f"    {_cstr(p.name)}" for p in profs))
    parts.append("\n};\n\n")
    parts.append(f"const char *const ngq_prof_title = "
                 f"{_cstr(profs[0].title)};\n\n")

    parts.append("const ngq_professor ngq_professors[NGQ_PROFESSOR_COUNT]"
                 " = {\n")
    parts.append(",\n".join(
        f"    {{ {p.target_tile}, {p.time_limit_sec}, {p.battle_target}, "
        f"{p.spell_reward}, {p.portrait} }}  /* {p.name} */"
        for p in profs))
    parts.append("\n};\n")

    with open(os.path.join(out_dir, "quest_config.c"), "w") as f:
        f.write("".join(parts))
    return ["quest_config.h", "quest_config.c"]
