"""Emit animation parameter data (gen/anim_tables.c) and the editor
manifest (gen/anim_manifest.json).

The C table is the retail source of truth; under DEBUG_BUILD the
runtime mirrors it into WRAM (symbol `anim_params`) where the
animation editor and harness poke values live. The manifest describes
every field — byte offset within the mirror, type, range, default —
so editor UI is generated from data, never hardcoded.
"""

import json
import os

SOURCE = """\
/* Auto-generated by gbforge (gen_anim) — do not edit. */
#include "anim.h"

const rt_anim_params anim_params_rom = {{
    {flash_hold},   /* flash_hold   */
    {clear_hold},   /* clear_hold   */
    {pass_gap},   /* pass_gap     */
    {{ {gravity} }},  /* gravity_delay */
    {swap_frames},  /* swap_frames  */
    {{ {curve} }},  /* swap_curve   */
    {shake_frames},   /* shake_frames */
    {{ {shake_dx} }},  /* shake_dx (int8) */
    {{ {shake_dy} }},  /* shake_dy (int8) */
    {sparkle_frames},   /* sparkle_frames */
    {wiggle_steps},   /* wiggle_steps  */
    {wiggle_step_frames},   /* wiggle_step_frames */
    {{ {wiggle_offsets} }}   /* wiggle_offsets (int8) */
}};
"""


def _fields(a):
    """(name, offset, size, default, range) for every tunable —
    must mirror rt_anim_params' layout exactly."""
    out = []
    off = 0

    def f(name, default, lo, hi, count=1):
        nonlocal off
        out.append({"name": name, "offset": off, "count": count,
                    "default": default, "min": lo, "max": hi})
        off += count

    f("flash_hold", a.flash.hold, 0, 60)
    f("clear_hold", a.timing.clear_hold, 0, 60)
    f("pass_gap", a.timing.pass_gap, 0, 60)
    f("gravity_delay", list(a.gravity.delays), 1, 12, count=8)
    f("swap_frames", len(a.swap.curve), 1, 16)
    curve = list(a.swap.curve) + [16] * (16 - len(a.swap.curve))
    f("swap_curve", curve, 0, 16, count=16)
    f("shake_frames", len(a.shake.dx), 0, 8)
    dx = list(a.shake.dx) + [0] * (8 - len(a.shake.dx))
    dy = list(a.shake.dy) + [0] * (8 - len(a.shake.dy))
    f("shake_dx", dx, -4, 4, count=8)
    f("shake_dy", dy, -4, 4, count=8)
    f("sparkle_frames", a.sparkle.phase_frames, 1, 30)
    f("wiggle_steps", len(a.wiggle.offsets), 0, 8)
    f("wiggle_step_frames", a.wiggle.step_frames, 1, 30)
    wo = list(a.wiggle.offsets) + [0] * (8 - len(a.wiggle.offsets))
    f("wiggle_offsets", wo, -4, 4, count=8)
    return out


def emit(game, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    a = game.animations
    a.swap.validate()

    a.shake.validate()
    a.wiggle.validate()
    curve = list(a.swap.curve) + [16] * (16 - len(a.swap.curve))
    sdx = list(a.shake.dx) + [0] * (8 - len(a.shake.dx))
    sdy = list(a.shake.dy) + [0] * (8 - len(a.shake.dy))
    with open(os.path.join(out_dir, "anim_tables.c"), "w") as f:
        f.write(SOURCE.format(
            flash_hold=a.flash.hold,
            clear_hold=a.timing.clear_hold,
            pass_gap=a.timing.pass_gap,
            gravity=", ".join(str(d) for d in a.gravity.delays),
            swap_frames=len(a.swap.curve),
            curve=", ".join(str(c) for c in curve),
            shake_frames=len(a.shake.dx),
            shake_dx=", ".join(str(v) for v in sdx),
            shake_dy=", ".join(str(v) for v in sdy),
            sparkle_frames=a.sparkle.phase_frames,
            wiggle_steps=len(a.wiggle.offsets),
            wiggle_step_frames=a.wiggle.step_frames,
            wiggle_offsets=", ".join(
                str(v) for v in list(a.wiggle.offsets)
                + [0] * (8 - len(a.wiggle.offsets))),
        ))

    manifest = {
        "mirror_symbol": "anim_params",
        "rom_symbol": "anim_params_rom",
        "fields": _fields(a),
    }
    with open(os.path.join(out_dir, "anim_manifest.json"), "w") as f:
        json.dump(manifest, f, indent=1)
    return ["anim_tables.c", "anim_manifest.json"]
