"""Emit the ability table (gen/ability_config.{h,c})."""

import os

from . import gen_audio

HEADER = """\
/* Auto-generated by gbforge (gen_abilities) — do not edit. */
#ifndef GEN_ABILITY_CONFIG_H_INCLUDED
#define GEN_ABILITY_CONFIG_H_INCLUDED

#include "ability.h"

#define NG_ABILITY_COUNT {count}
{defines}
extern const ng_ability ng_abilities[NG_ABILITY_COUNT];

#endif
"""

SOURCE = """\
/* Auto-generated by gbforge (gen_abilities) — do not edit. */
#include "ability.h"
#include "ability_config.h"

const ng_ability ng_abilities[NG_ABILITY_COUNT] = {{
{rows}
}};
"""


def emit(game, out_dir, res_dir=None):
    abilities = getattr(game, "abilities", [])
    if not abilities:
        return []
    os.makedirs(out_dir, exist_ok=True)
    if res_dir is None:
        res_dir = os.path.join(out_dir, "..", "res")
    # the sfx enum is only needed when an ability names a cast
    # sound — a game without audio must not require a sound res
    sfx_ids = None
    if any(getattr(a, "cast_sfx", None) for a in abilities):
        sfx_ids = gen_audio.load_sfx_ids(res_dir)

    def sfx_of(a):
        name = getattr(a, "cast_sfx", None)
        if name is None:
            return 0xFF
        return sfx_ids[name]
    defines = "".join(
        f"#define NG_AB_{a.name.upper()} {i}\n"
        for i, a in enumerate(abilities))
    rows = ",\n".join(
        f"    {{ {a.cost_of('fire')}, {a.cost_of('water')}, "
        f"{a.cost_of('earth')}, {a.targeting}, {a.target_filter}, "
        f"{a.op}, {a.op_arg}, {getattr(a, 'unlock_cost', 0)}, "
        f"{sfx_of(a)} }}  /* {a.name} */"
        for a in abilities)
    with open(os.path.join(out_dir, "ability_config.h"), "w") as f:
        f.write(HEADER.format(count=len(abilities), defines=defines))
    with open(os.path.join(out_dir, "ability_config.c"), "w") as f:
        f.write(SOURCE.format(rows=rows))
    return ["ability_config.h", "ability_config.c"]
