"""Emit the audio tables (gen/audio_config.{h,c}).

Sound-effect names resolve against the editor-owned res enum
(the game's res/sfx_data.h) — parsed, never regenerated, same frozen
boundary as the tile headers. The tables are HOME-resident: the glue
and the VBL-pumped driver read them from any bank context.
"""

import os
import re

from ..model.audio import EVENTS, EXTRA_SCENES

NGAU_NONE = 0xFF


def load_sfx_ids(res_dir):
    """Parse the SFX_* enum out of the res header."""
    path = os.path.join(res_dir, "sfx_data.h")
    ids = {}
    for m in re.finditer(r"(SFX_[A-Z0-9_]+)\s*=\s*(\d+)", open(path).read()):
        ids[m.group(1)] = int(m.group(2))
    return ids


HEADER = """\
/* Auto-generated by gbforge (gen_audio) — do not edit. */
#ifndef GEN_AUDIO_CONFIG_H_INCLUDED
#define GEN_AUDIO_CONFIG_H_INCLUDED

#include <stdint.h>

#include "sound_glue.h"   /* NGAU_EV_* vocabulary lives in the runtime */

#if NGAU_EVENT_COUNT != {event_count}
#error "audio event vocabulary drifted between model and runtime"
#endif

/* scenes: title, then modes in game order, then extras */
{scene_defines}
#define NGAU_SCENE_COUNT {scene_count}

extern const uint8_t ngau_event_sfx[NGAU_EVENT_COUNT];
extern const uint8_t *const ngau_scene_music[NGAU_SCENE_COUNT];
extern const uint8_t ngau_scene_music_bank[NGAU_SCENE_COUNT];
extern const uint16_t ngau_scene_music_len[NGAU_SCENE_COUNT];

#endif
"""

SOURCE = """\
/* Auto-generated by gbforge (gen_audio) — do not edit. */
#include <stdint.h>
#include "audio_config.h"
#include "music_data.h"   /* per-track _BANK/_LEN macros */

{track_externs}
const uint8_t ngau_event_sfx[NGAU_EVENT_COUNT] = {{
{event_rows}
}};

const uint8_t *const ngau_scene_music[NGAU_SCENE_COUNT] = {{
{scene_rows}
}};

const uint8_t ngau_scene_music_bank[NGAU_SCENE_COUNT] = {{
{scene_banks}
}};

const uint16_t ngau_scene_music_len[NGAU_SCENE_COUNT] = {{
{scene_lens}
}};
"""


def emit(game, out_dir, res_dir=None):
    theme = getattr(game, "audio", None)
    if theme is None:
        return []
    if res_dir is None:
        res_dir = os.path.join(out_dir, "..", "res")
    sfx_ids = load_sfx_ids(res_dir)
    os.makedirs(out_dir, exist_ok=True)

    scenes = ["title"] + [m.name for m in game.modes] + EXTRA_SCENES

    scene_defines = "".join(
        f"#define NGAU_SCENE_{s.upper()} {i}\n" for i, s in enumerate(scenes))

    rows = []
    for e in EVENTS:
        name = theme.events.get(e)
        if name is None:
            rows.append(f"    NGAU_NONE  /* {e} */")
        else:
            if name not in sfx_ids:
                raise KeyError(f"audio event {e!r}: {name} not found in "
                               f"res/sfx_data.h")
            rows.append(f"    {sfx_ids[name]}  /* {e}: {name} */")

    tracks = sorted({t for t in theme.music.values() if t})
    track_externs = "".join(f"extern const uint8_t {t}[];\n" for t in tracks)

    scene_rows, scene_banks, scene_lens = [], [], []
    for s in scenes:
        t = theme.music.get(s)
        scene_rows.append(f"    {t if t else '0'}  /* {s} */")
        scene_banks.append(f"    {t + '_BANK' if t else '0'}  /* {s} */")
        scene_lens.append(f"    {t + '_LEN' if t else '0'}  /* {s} */")

    with open(os.path.join(out_dir, "audio_config.h"), "w") as f:
        f.write(HEADER.format(event_count=len(EVENTS),
                              scene_defines=scene_defines,
                              scene_count=len(scenes)))
    with open(os.path.join(out_dir, "audio_config.c"), "w") as f:
        f.write(SOURCE.format(track_externs=track_externs,
                              event_rows=",\n".join(rows),
                              scene_rows=",\n".join(scene_rows),
                              scene_banks=",\n".join(scene_banks),
                              scene_lens=",\n".join(scene_lens)))
    return ["audio_config.h", "audio_config.c"]
