"""Emit the scoring tables (gen/scoring_config.{h,c}).

One source for every reward number: the engine indexes these tables
from every mode's resolve path, so scoring cannot diverge by mode.
Same bank as the engine (its hot path reads them directly).
"""

import os

HEADER = """\
/* Auto-generated by gbforge (gen_scoring) — do not edit. */
#ifndef GEN_SCORING_CONFIG_H_INCLUDED
#define GEN_SCORING_CONFIG_H_INCLUDED

#include <stdint.h>

/* manna per manna-run, indexed by run length (clamp index to 8) */
extern const uint8_t ng_manna_for_run[9];

/* knowledge per tile in a metal run, indexed by tile type */
extern const uint16_t ng_knowledge_per_tier[12];

extern const uint8_t ng_manna_cap;       /* fx.manna_cap overrides */
extern const uint16_t ng_knowledge_cap;

#endif
"""

SOURCE = """\
/* Auto-generated by gbforge (gen_scoring) — do not edit.
 * Same bank as engine.c: its award path indexes these directly. */
#ifdef __SDCC
#pragma bank 1
#endif

#include "scoring_config.h"

const uint8_t ng_manna_for_run[9] = {{ {manna} }};
const uint16_t ng_knowledge_per_tier[12] = {{ {know} }};
const uint8_t ng_manna_cap = {manna_cap};
const uint16_t ng_knowledge_cap = {know_cap};
"""


def emit(game, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    s = getattr(game, "scoring", None)
    if s is None:
        from gbforge.model.scoring import Scoring
        s = Scoring()
    s.validate()
    with open(os.path.join(out_dir, "scoring_config.h"), "w") as f:
        f.write(HEADER)
    with open(os.path.join(out_dir, "scoring_config.c"), "w") as f:
        f.write(SOURCE.format(
            manna=", ".join(str(v) for v in s.manna_for_run),
            know=", ".join(str(v) for v in s.knowledge_per_tier),
            manna_cap=s.manna_cap,
            know_cap=s.knowledge_cap))
    return ["scoring_config.h", "scoring_config.c"]
