"""Emit the per-mode flow-config table (gen/mode_config.{h,c}).

The runtime's flow.c reads one ng_mode_config per mode — the data
that the original hand-written game expressed as six diverged copies of the swap
choreography plus scattered booleans. Output is deterministic
(sorted, no timestamps) so incremental builds stay stable.
"""

import os

HEADER = """\
/* Auto-generated by gbforge (gen_modes) — do not edit.
 * Source: the game definition's Mode list. */
#ifndef GEN_MODE_CONFIG_H_INCLUDED
#define GEN_MODE_CONFIG_H_INCLUDED

#include <stdint.h>

#include "flow.h"

#define NG_MODE_COUNT {count}
{defines}
extern const ng_mode_config ng_modes[NG_MODE_COUNT];

#endif
"""

SOURCE = """\
/* Auto-generated by gbforge (gen_modes) — do not edit. */
#include "mode_config.h"

const ng_mode_config ng_modes[NG_MODE_COUNT] = {{
{rows}
}};
"""


def emit(game, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    defines = "".join(
        f"#define NG_MODE_{m.name.upper()} {i}\n"
        for i, m in enumerate(game.modes))
    rows = ",\n".join(
        f"    {{ {int(m.refill)}, {m.shake_run}, {m.shake_passes} }}"
        f"  /* {m.name} */"
        for m in game.modes)

    with open(os.path.join(out_dir, "mode_config.h"), "w") as f:
        f.write(HEADER.format(count=len(game.modes), defines=defines))
    with open(os.path.join(out_dir, "mode_config.c"), "w") as f:
        f.write(SOURCE.format(rows=rows))
    return ["mode_config.h", "mode_config.c"]
