"""Emit overlay definitions (gen/ui_overlays.{h,c}).

Border tiles and palettes are emitted as the SYMBOLIC C macros from
the editor-owned res headers (UI_TILE_*, PAL_*) — the C compiler
resolves them, so sprite-editor re-exports can never desynchronize
the generated UI.
"""

import os

HEADER = """\
/* Auto-generated by gbforge (gen_ui) — do not edit. */
#ifndef GEN_UI_OVERLAYS_H_INCLUDED
#define GEN_UI_OVERLAYS_H_INCLUDED

#include "ui_core.h"

{externs}
#endif
"""

SOURCE = """\
/* Auto-generated by gbforge (gen_ui) — do not edit. */
#include "ui_core.h"
#include "ui_overlays.h"

#include "tiles_data.h"
#include "palettes.h"

{bodies}
"""


def _overlay_body(o):
    b = o.border
    lines_name = f"lines_{o.name}"
    rows = ",\n".join(
        f'    {{ {dy}, "{text}" }}' for dy, text in o.lines)
    lines_decl = (
        f"static const ng_overlay_line {lines_name}[{len(o.lines)}] = {{\n"
        f"{rows}\n}};\n")
    return (
        f"{lines_decl}"
        f"const ng_overlay ovl_{o.name} = {{\n"
        f"    {{ {o.pos[0]}, {o.pos[1]}, {o.size[0]}, {o.size[1]},\n"
        f"      {b.c_palette},\n"
        f"      {b.c_tile('top')}, {b.c_tile('bottom')},\n"
        f"      {b.c_tile('left')}, {b.c_tile('right')},\n"
        f"      {b.c_tile('corner_tl')}, {b.c_tile('corner_tr')},\n"
        f"      {b.c_tile('corner_bl')}, {b.c_tile('corner_br')},\n"
        f"      {b.c_tile('fill')} }},\n"
        f"    {lines_name},\n"
        f"    {len(o.lines)}\n"
        f"}};\n")


def emit(game, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    overlays = getattr(game, "overlays", [])
    externs = "".join(
        f"extern const ng_overlay ovl_{o.name};\n" for o in overlays)
    bodies = "\n".join(_overlay_body(o) for o in overlays)
    with open(os.path.join(out_dir, "ui_overlays.h"), "w") as f:
        f.write(HEADER.format(externs=externs))
    with open(os.path.join(out_dir, "ui_overlays.c"), "w") as f:
        f.write(SOURCE.format(bodies=bodies))
    return ["ui_overlays.h", "ui_overlays.c"]
