"""Emit the title screen + menu data (gen/title_config.{h,c}).

Menu labels are BAKED against the res VWF font: pixel-centered tile
runs (same pipeline as overlays), with each item's arrow position
computed from where its ink actually starts. Deco palettes compile
to PAL_* symbols; the title palette set to an RGB555 table — colors
are definition data, deliberately independent of the sprite
editor's bg palettes (the original game's rainbow-bar
guarantee, now structural).
"""

import os

from gbforge.codegen.gen_ui import MerlinFont, _fmt_bytes

MENU_RUN_TILES = 12   # baked run per item; 3 items = 36 pool tiles
ARROW_GAP_TILES = 2   # arrow sits two tiles left of the label ink

HEADER = """\
/* Auto-generated by gbforge (gen_title) — do not edit. */
#ifndef GEN_TITLE_CONFIG_H_INCLUDED
#define GEN_TITLE_CONFIG_H_INCLUDED

#include "title.h"

extern const ng_title ng_title_screen;

#endif
"""

SOURCE = """\
/* Auto-generated by gbforge (gen_title) — do not edit.
 * Same bank as title.c: it uploads the baked label tiles while
 * this bank is mapped. */
#ifdef __SDCC
#pragma bank 2
#endif

#include "title.h"
#include "title_config.h"

#include "tiles_data.h"
#include "palettes.h"

#define RGB555(r, g, b) ((uint16_t)((r) | ((g) << 5) | ((b) << 10)))

static const uint16_t title_palettes[{npal} * 4] = {{
{palettes}
}};

{labels}
static const ng_menu_item menu_items[{nitems}] = {{
{items}
}};

const ng_title ng_title_screen = {{
    {logo_letters}, {logo_x}, {logo_y},
    {deco_x}, {deco_y}, {deco_n},
    {{ {deco_attrs} }},
    title_palettes,
    {{ {run_x}, {menu_y}, {row_step}, {nitems}, menu_items }}
}};
"""


def _label_tiles(label):
    out = []
    for ch in label.upper():
        if "A" <= ch <= "Z":
            out.append(f"UI_TILE_LETTER_A + {ord(ch) - ord('A')}")
        elif "0" <= ch <= "9":
            out.append(f"UI_TILE_DIGIT_0 + {ord(ch) - ord('0')}")
        else:
            out.append("UI_TILE_BLANK")
    return out


def emit(game, out_dir):
    t = getattr(game, "title", None)
    if t is None:
        return []
    os.makedirs(out_dir, exist_ok=True)

    pal_rows = []
    for pal in t.palettes:
        row = ", ".join(f"RGB555({r}, {g}, {b})" for r, g, b in pal)
        pal_rows.append(f"    {row},")
    palettes = "\n".join(pal_rows)

    font = MerlinFont.load(out_dir)
    if font is None:
        raise SystemExit(
            "gen_title: res/merlin_font.c not found — baked menu "
            "labels require the VWF font source")

    run_x = (20 - MENU_RUN_TILES) // 2
    labels = ""
    item_rows = []
    for i, (label, value) in enumerate(t.menu.items):
        px = font.width_px(label)
        if px > MENU_RUN_TILES * 8:
            raise SystemExit(
                f"gen_title: menu label '{label}' is {px}px, run is "
                f"{MENU_RUN_TILES * 8}px")
        data = font.bake_line(label, MENU_RUN_TILES)
        ink_tile = ((MENU_RUN_TILES * 8 - px) // 2) // 8
        arrow_x = run_x + ink_tile - ARROW_GAP_TILES
        if arrow_x < 0:
            arrow_x = 0
        labels += (f'/* "{label}" — pixel-centered; ink starts tile '
                   f"{ink_tile} of the run */\n"
                   f"static const uint8_t label_{i}[{len(data)}] = {{\n"
                   f"{_fmt_bytes(data)}\n}};\n")
        item_rows.append(
            f"    {{ label_{i}, {MENU_RUN_TILES}, {value}, {arrow_x} }}")

    # An empty bar still needs a valid C initializer; the runtime
    # skips drawing entirely when deco_n is 0.
    deco_attrs = (", ".join(f"PAL_{p.upper()}" for p in t.deco_palettes)
                  or "0")

    with open(os.path.join(out_dir, "title_config.h"), "w") as f:
        f.write(HEADER)
    with open(os.path.join(out_dir, "title_config.c"), "w") as f:
        f.write(SOURCE.format(
            npal=len(t.palettes),
            palettes=palettes,
            labels=labels,
            nitems=len(t.menu.items),
            items=",\n".join(item_rows),
            logo_letters=t.logo_letters,
            logo_x=t.logo_pos[0], logo_y=t.logo_pos[1],
            deco_x=t.deco_pos[0], deco_y=t.deco_pos[1],
            deco_n=len(t.deco_palettes),
            deco_attrs=deco_attrs,
            run_x=run_x, menu_y=t.menu.pos[1],
            row_step=t.menu.row_step,
        ))
    return ["title_config.h", "title_config.c"]
