/* Auto-generated by scripts/gen_placeholder_res.py — do not
 * edit. Deliberately-placeholder assets satisfying the
 * gbforge runtime's asset contract. */
#ifndef MERLIN_FONT_H
#define MERLIN_FONT_H

/* VWF tile pool — the runtime asset contract.
 *
 * ui_show_overlay() uploads an overlay's baked text spans starting at
 * VWF_POOL_BASE. The pool sits above every statically-loaded tile so
 * an overlay can never clobber board, UI, or icon graphics; it DOES
 * share the ghost/logo range, which is safe because the two never
 * appear on screen together (see tiles_data.h).
 */
#define VWF_POOL_BASE  220
#define VWF_POOL_SIZE  36

#endif
