/* Auto-generated by scripts/gen_placeholder_res.py — do not
 * edit. Deliberately-placeholder assets satisfying the
 * gbforge runtime's asset contract. */
#ifndef PALETTES_H
#define PALETTES_H

#include <stdint.h>

#define PAL_FIRE 0
#define PAL_WATER 1
#define PAL_EARTH 2
#define PAL_BRONZE 3
#define PAL_DARK 4
#define PAL_GOLD 5
#define PAL_RUBY 6
#define PAL_SILVER 7
#define PAL_CURSOR 0
#define PAL_CURSOR_OPPONENT 4
#define PAL_GHOST_HINT 5
#define PAL_GHOST_UNSOLVABLE 6
#define PAL_A 0
#define PAL_B 1
#define PAL_RED 6
#define PAL_YELLOW 5
#define PAL_TARGETING 7

extern const uint16_t bg_palettes[32];
extern const uint16_t sprite_palettes[32];

#endif
