#include <gb/cgb.h>
#include "palettes.h"

// Generated by GBSpriteEditor — do not edit manually

const uint16_t bg_palettes[8 * 4] = {
    // Fire (0)
    RGB(31, 31, 31), RGB(31, 22, 24), RGB(26, 4 , 8 ), RGB(10, 1 , 2 ), 
    // Water (1)
    RGB(31, 31, 31), RGB(22, 31, 22), RGB(4 , 22, 8 ), RGB(1 , 8 , 2 ), 
    // Earth (2)
    RGB(31, 31, 31), RGB(31, 30, 20), RGB(28, 22, 4 ), RGB(12, 9 , 1 ), 
    // Bronze (3)
    RGB(31, 31, 31), RGB(20, 20, 24), RGB(8 , 8 , 12), RGB(2 , 2 , 4 ), 
    // Dark (4)
    RGB(31, 31, 31), RGB(24, 24, 24), RGB(16, 16, 16), RGB(0 , 0 , 0 ), 
    // Gold (5)
    RGB(31, 31, 31), RGB(28, 26, 8 ), RGB(22, 18, 4 ), RGB(8 , 6 , 0 ), 
    // Ruby (6)
    RGB(31, 31, 31), RGB(30, 12, 12), RGB(24, 4 , 4 ), RGB(8 , 0 , 0 ), 
    // Silver (7)
    RGB(31, 31, 31), RGB(24, 24, 26), RGB(14, 14, 16), RGB(0 , 0 , 0 )
};
