/* Auto-generated by scripts/gen_placeholder_res.py — do not
 * edit. Deliberately-placeholder assets satisfying the
 * gbforge runtime's asset contract. */
#ifndef SPRITES_DATA_H
#define SPRITES_DATA_H

#include <stdint.h>

#define CURSOR_SPRITE_BASE 0
#define CURSOR_TILE_NORMAL 0
#define CURSOR_TILE_INVERTED 4
#define CURSOR_SPRITE_COUNT 4
#define CURSOR_TOTAL_TILES 8

#define KNOWLEDGE_SPRITE_BASE 4
#define KNOWLEDGE_TILE_BASE 8
#define KNOWLEDGE_TILE_K 8
#define KNOWLEDGE_TILE_0 9
#define KNOWLEDGE_SPRITE_COUNT 5
#define KNOWLEDGE_TOTAL_TILES 11

#define BURST_SPRITE_BASE 9
#define BURST_SPRITE_COUNT 3
#define BURST_TILE_BASE 19
#define BURST_TILE_DOT 19
#define BURST_TILE_SMALL 20
#define BURST_TILE_FULL 21
#define BURST_TOTAL_TILES 3

#define FLOAT_SPRITE_BASE 12
#define FLOAT_TILE_PLUS 22
#define FLOAT_TOTAL_TILES 1
#define MAX_FLOATING_NUMS 4

#define CHAIN_SPRITE_BASE 20
#define CHAIN_DIGIT_TILE_TOP 23
#define CHAIN_DIGIT_TILE_BOT 30
#define CHAIN_WORD_TILE_TOP 37
#define CHAIN_WORD_TILE_BOT 44
#define CHAIN_WORD_COLS 7
#define CHAIN_TOTAL_TILES 28

#define HINT_SPRITE_BASE 36
#define GHOST_CURSOR_A_BASE 4    /* hint bracket A: aliases knowledge */
#define GHOST_CURSOR_B_BASE 36   /* hint bracket B: aliases hint/moves */
#define HINT_SPRITE_COUNT 4
#define HINT_TILE_BASE 51

#define MOVES_SPR_TILE_M 55
#define MOVES_SPR_TILE_V 56
#define MOVES_SPR_TILE_D0 57

#define OPP_KNOWLEDGE_SPRITE_BASE 20
#define OPP_KNOWLEDGE_SPRITE_COUNT 5
#define OPP_KNOWLEDGE_TILE_C 67
#define OPP_KNOWLEDGE_TOTAL_TILES 1

#define SWAP_TILE_A 68
#define SWAP_TILE_B 72
#define SWAP_SPRITE_A_BASE 25
#define SWAP_SPRITE_B_BASE 29
#define SWAP_PAL_A 4
#define SWAP_PAL_B 5

extern const uint8_t cursor_sprite_data[];
extern const uint8_t knowledge_sprite_data[];
extern const uint8_t burst_sprite_data[];
extern const uint8_t float_sprite_data[];
extern const uint8_t chain_sprite_data[];
extern const uint8_t hint_sprite_data[];
extern const uint8_t moves_sprite_data[];
extern const uint8_t opp_knowledge_sprite_data[];

#endif
