/* Auto-generated by scripts/gen_placeholder_res.py — do not
 * edit. Deliberately-placeholder assets satisfying the
 * gbforge runtime's asset contract. */
#ifndef TILES_DATA_H
#define TILES_DATA_H

#include <stdint.h>

#define TILE_EMPTY 0
#define TILE_TYPE_COUNT 12
#define HW_TILES_PER_LOGICAL 4
#define HW_TILE_BASE(type) ((type) * HW_TILES_PER_LOGICAL)
#define TOTAL_GAME_HW_TILES (TILE_TYPE_COUNT * HW_TILES_PER_LOGICAL)

#define UI_TILE_BASE TOTAL_GAME_HW_TILES
#define UI_TILE_DIGIT_0      (UI_TILE_BASE + 0)
#define UI_TILE_SOLID        (UI_TILE_BASE + 10)
#define UI_TILE_BLANK        (UI_TILE_BASE + 11)
#define UI_TILE_LABEL_K      (UI_TILE_BASE + 12)
#define UI_TILE_LETTER_A     (UI_TILE_BASE + 14)
#define UI_TILE_ARROW        (UI_TILE_BASE + 40)
#define UI_TILE_CHECK        (UI_TILE_BASE + 41)
#define UI_TILE_OVL_BORDER_TOP   (UI_TILE_BASE + 42)
#define UI_TILE_OVL_BORDER_BOT   (UI_TILE_BASE + 43)
#define UI_TILE_OVL_BORDER_LEFT  (UI_TILE_BASE + 44)
#define UI_TILE_OVL_BORDER_RIGHT (UI_TILE_BASE + 45)
#define UI_TILE_TRI_UP       (UI_TILE_BASE + 46)
#define UI_TILE_TRI_DOWN     (UI_TILE_BASE + 47)
#define UI_TILE_SEL_L        (UI_TILE_BASE + 48)
#define UI_TILE_SEL_R        (UI_TILE_BASE + 49)
#define UI_TILE_BORDER_TOP   (UI_TILE_BASE + 50)
#define UI_TILE_BORDER_BOT   (UI_TILE_BASE + 51)
#define UI_TILE_BORDER_LEFT  (UI_TILE_BASE + 52)
#define UI_TILE_BORDER_RIGHT (UI_TILE_BASE + 53)
#define UI_TILE_CORNER_TL    (UI_TILE_BASE + 54)
#define UI_TILE_CORNER_TR    (UI_TILE_BASE + 55)
#define UI_TILE_CORNER_BL    (UI_TILE_BASE + 56)
#define UI_TILE_CORNER_BR    (UI_TILE_BASE + 57)
#define UI_TILE_SOLID3       (UI_TILE_BASE + 58)
#define UI_TILE_ROUND2       (UI_TILE_BASE + 59)

/* Ghost (faded) game-tile variants: refill drop-in transit tiles.
 * Shares the title logo's tile range (188+): the logo is
 * title-only and ghosts are game-only; each screen's gfx load
 * overwrites the other's slice. */
#define GHOST_TILE_BASE 188
#define HW_TILE_BASE_GHOST(type) (GHOST_TILE_BASE + (type) * HW_TILES_PER_LOGICAL)
#define UI_TILE_ROUND3       (UI_TILE_BASE + 60)
#define UI_TILE_OVL_CORNER_TL (UI_TILE_BASE + 61)
#define UI_TILE_OVL_CORNER_TR (UI_TILE_BASE + 62)
#define UI_TILE_OVL_CORNER_BL (UI_TILE_BASE + 63)
#define UI_TILE_OVL_CORNER_BR (UI_TILE_BASE + 64)
#define UI_TILE_TRI_UP_DIS   (UI_TILE_BASE + 66)
#define UI_TILE_TRI_DOWN_DIS (UI_TILE_BASE + 67)
#define UI_TILE_ROUND_OV1    (UI_TILE_BASE + 68)
#define UI_TILE_ROUND_S1     (UI_TILE_BASE + 69)
#define UI_TILE_ROUND_OV2    (UI_TILE_BASE + 70)
#define UI_TILE_ROUND_S2     (UI_TILE_BASE + 71)
#define UI_TILE_DIGIT_S1_0   (UI_TILE_BASE + 72)
#define UI_TILE_DIGIT_S2_0   (UI_TILE_BASE + 82)
#define UI_TILE_DIGIT_OV2_0  (UI_TILE_BASE + 92)
#define UI_TILE_SMALL_DOT    (UI_TILE_BASE + 102)
#define UI_TILE_SMALL_DIGIT_0 (UI_TILE_BASE + 103)
#define UI_TILE_COLON        (UI_TILE_BASE + 115)
#define UI_TILE_DIGIT_OV1_0  (UI_TILE_BASE + 116)
#define UI_TILE_COUNT 126
#define TOTAL_HW_TILES (TOTAL_GAME_HW_TILES + UI_TILE_COUNT)

#define SPELL_ICON_COUNT 14
#define SPELL_ICON_TILE_BASE TOTAL_HW_TILES
#define UI_TILE_SPARK (SPELL_ICON_TILE_BASE + 0)

extern const uint8_t tile_data[];
extern const uint8_t ui_tile_data[];
extern const uint8_t spell_icon_tile_data[];
extern const uint8_t ghost_tile_data[];
extern const uint8_t tile_palette_map[][4];

#endif
