/* Auto-generated by scripts/gen_placeholder_res.py — do not
 * edit. Deliberately-placeholder assets satisfying the
 * gbforge runtime's asset contract. */
#ifndef TITLE_LOGO_H
#define TITLE_LOGO_H

#include <stdint.h>
#include "tiles_data.h"

#define TITLE_LOGO_TILE_BASE (SPELL_ICON_TILE_BASE + SPELL_ICON_COUNT)
#define TITLE_LOGO_TILE_COUNT (8 * 4)

extern const uint8_t title_logo_tiles[];

#endif
