import Foundation

/// Exports tile and palette data as C source matching the res
/// contract the runtime compiles against (see res/*.h).
enum CExporter {

    /// Legacy single-string export for the Export C Code sheet.
    static func export(document: TileDocument) -> String {
        var out = ""
        out += "// Generated by GBSpriteEditor\n"
        out += "// \(document.tiles.count) tiles, \(document.palettes.count) palettes\n\n"
        out += "#include <stdint.h>\n\n"

        // Tile data
        out += formatTileData(tiles: document.tiles)
        out += "\n"

        // Palette data
        out += formatPalettesInline(palettes: document.palettes)
        out += "\n"

        // Per-quadrant palette map
        out += formatPaletteMap(tiles: document.tiles)

        // Spell icons
        out += "\n"
        out += generateSpellIconsC(spellIcons: document.spellIcons)

        // Spell cast tiles
        out += "\n"
        out += generateSpellCastTilesC(spellCastTiles: document.spellCastTiles)

        // Indicator tiles
        out += "\n"
        out += generateIndicatorTilesC(indicatorTiles: document.indicatorTiles)

        return out
    }

    /// Write separate `tiles_data.c`, `palettes.c`, and `spell_icons.c` to the given directory.
    static func exportToDirectory(document: TileDocument, directory: URL) throws {
        let tilesC = generateTilesDataC(document: document)
        let palettesC = generatePalettesC(document: document)
        let spellIconsC = generateSpellIconsC(spellIcons: document.spellIcons)
            + "\n" + generateSpellCastTilesC(spellCastTiles: document.spellCastTiles)
        let indicatorTilesC = generateIndicatorTilesC(indicatorTiles: document.indicatorTiles)

        try tilesC.write(to: directory.appendingPathComponent("tiles_data.c"),
                         atomically: true, encoding: .utf8)
        try palettesC.write(to: directory.appendingPathComponent("palettes.c"),
                            atomically: true, encoding: .utf8)
        try spellIconsC.write(to: directory.appendingPathComponent("spell_icons.c"),
                              atomically: true, encoding: .utf8)
        try indicatorTilesC.write(to: directory.appendingPathComponent("indicator_tiles.c"),
                                  atomically: true, encoding: .utf8)
    }

    /// Write game-compatible C files to the given directory.
    /// Uses [][4] palette map format, always exports exactly 8 palettes, and omits sprite palettes.
    /// tile_data[] goes to tiles_gfx.c (ROM bank 2) if it exists, otherwise tiles_data.c.
    static func exportToGameDirectory(document: TileDocument, directory: URL) throws {
        // Write the palette map using the same constants palettes.h declares,
        // so a future re-index of a palette slot carries the table with it.
        let constants = PaletteConstants.load(fromGameDirectory: directory) ?? .empty

        let palettesC = generateGamePalettesC(document: document)
        let paletteMapC = generateGamePaletteMapC(document: document, constants: constants)

        try paletteMapC.write(to: directory.appendingPathComponent("tiles_data.c"),
                              atomically: true, encoding: .utf8)
        try palettesC.write(to: directory.appendingPathComponent("palettes.c"),
                            atomically: true, encoding: .utf8)

        // Write tile_data[] to tiles_gfx.c if it exists (split for ROM banking),
        // otherwise include it in tiles_data.c
        let gfxURL = directory.appendingPathComponent("tiles_gfx.c")
        if FileManager.default.fileExists(atPath: gfxURL.path) {
            let tileGfxC = generateGameTileGfxC(document: document)
            try tileGfxC.write(to: gfxURL, atomically: true, encoding: .utf8)
        } else {
            // Append tile data into tiles_data.c
            let tileData = "\n" + formatTileData(tiles: document.tiles)
            let handle = try FileHandle(forWritingTo: directory.appendingPathComponent("tiles_data.c"))
            handle.seekToEndOfFile()
            handle.write(tileData.data(using: .utf8)!)
            handle.closeFile()
        }

        // Write spell_icons.c (includes cast tiles)
        let spellIconsC = generateSpellIconsC(spellIcons: document.spellIcons)
            + "\n" + generateSpellCastTilesC(spellCastTiles: document.spellCastTiles)
        try spellIconsC.write(to: directory.appendingPathComponent("spell_icons.c"),
                              atomically: true, encoding: .utf8)

        // Write indicator_tiles.c
        let indicatorTilesC = generateIndicatorTilesC(indicatorTiles: document.indicatorTiles)
        try indicatorTilesC.write(to: directory.appendingPathComponent("indicator_tiles.c"),
                                  atomically: true, encoding: .utf8)
    }

    // MARK: - Generated tiles_data.c

    private static func generateTilesDataC(document: TileDocument) -> String {
        var out = ""
        out += "#include <stdint.h>\n"
        out += "#include \"tiles_data.h\"\n"
        out += "#include \"palettes.h\"\n"
        out += "\n"
        out += "// Generated by GBSpriteEditor — do not edit manually\n"
        out += "\n"
        out += formatTileData(tiles: document.tiles)
        out += "\n"
        out += formatPaletteMap(tiles: document.tiles)
        return out
    }

    // MARK: - Generated palettes.c

    private static func generatePalettesC(document: TileDocument) -> String {
        var out = ""
        out += "#include <gb/cgb.h>\n"
        out += "#include \"palettes.h\"\n"
        out += "\n"
        out += "// Generated by GBSpriteEditor — do not edit manually\n"
        out += "\n"
        out += formatBgPalettes(palettes: document.palettes)
        out += "\n"
        out += formatSpritePalettes()
        return out
    }

    // MARK: - Formatting helpers

    private static func formatTileData(tiles: [GBTile16x16]) -> String {
        var out = "const uint8_t tile_data[] = {\n"

        for (tileIdx, tile) in tiles.enumerated() {
            out += "    // === \(tile.name) (\(tileIdx)) ===\n"
            let subLabels = ["top-left", "top-right", "bottom-left", "bottom-right"]
            for (subIdx, subTile) in tile.subTiles.enumerated() {
                out += "    // \(subLabels[subIdx]) 8x8\n"
                let bytes = subTile.encode()
                // Format as 4 bytes per line (2 rows of pixels)
                for row in stride(from: 0, to: 16, by: 4) {
                    out += "    "
                    for i in row..<(row + 4) {
                        out += String(format: "0x%02X,", bytes[i])
                        if i < row + 3 { out += " " }
                    }
                    // Add space between pairs for readability
                    out += "\n"
                }
            }
            if tileIdx < tiles.count - 1 {
                out += "\n"
            }
        }

        out += "};\n"
        return out
    }

    private static func formatPaletteMap(tiles: [GBTile16x16]) -> String {
        var out = "const uint8_t tile_palette_map[] = {\n"
        for tile in tiles {
            out += "    \(tile.paletteIndex),"
            out += "  // \(tile.name)\n"
        }
        out += "};\n"
        return out
    }

    private static func formatBgPalettes(palettes: [GBPalette]) -> String {
        var out = "const uint16_t bg_palettes[\(palettes.count) * 4] = {\n"
        for (i, palette) in palettes.enumerated() {
            out += "    // \(palette.name) (\(i))\n"
            out += "    "
            for (ci, color) in palette.colors.enumerated() {
                out += String(format: "RGB(%-2d, %-2d, %-2d)", color.r, color.g, color.b)
                if i < palettes.count - 1 || ci < 3 {
                    out += ", "
                }
            }
            out += "\n"
        }
        out += "};\n"
        return out
    }

    private static func formatSpritePalettes() -> String {
        var out = "const uint16_t sprite_palettes[1 * 4] = {\n"
        out += "    RGB(0,  0,  0),  RGB(31, 31, 31), RGB(24, 24, 24), RGB(0,  0,  0),\n"
        out += "};\n"
        return out
    }

    // MARK: - Game-directory generation (the res/ contract)

    /// tiles_data.c: palette map only (tile pixel data is in tiles_gfx.c)
    private static func generateGamePaletteMapC(document: TileDocument, constants: PaletteConstants) -> String {
        var out = ""
        out += "#include <stdint.h>\n"
        out += "#include \"tiles_data.h\"\n"
        out += "#include \"palettes.h\"\n"
        out += "\n"
        out += formatGamePaletteMap(tiles: document.tiles, constants: constants)
        return out
    }

    /// tiles_gfx.c: tile pixel data in ROM bank 2
    private static func generateGameTileGfxC(document: TileDocument) -> String {
        var out = ""
        out += "#pragma bank 2\n"
        out += "\n"
        out += "#include <stdint.h>\n"
        out += "#include \"tiles_data.h\"\n"
        out += "\n"
        out += "// Generated by GBSpriteEditor — do not edit manually\n"
        out += "\n"
        out += formatTileData(tiles: document.tiles)
        return out
    }

    private static func generateGamePalettesC(document: TileDocument) -> String {
        var out = ""
        out += "#include <gb/cgb.h>\n"
        out += "#include \"palettes.h\"\n"
        out += "\n"
        out += "// Generated by GBSpriteEditor — do not edit manually\n"
        out += "\n"
        out += formatGameBgPalettes(palettes: document.palettes)
        return out
    }

    /// Per-quadrant palette map: [][4] with the palette index repeated 4 times per tile.
    /// Entries are written as palettes.h constants where the header names the
    /// index, falling back to the literal. Clamps to max 7 (GBC hardware limit).
    private static func formatGamePaletteMap(tiles: [GBTile16x16], constants: PaletteConstants) -> String {
        let entries = tiles.map { tile -> String in
            let p = min(tile.paletteIndex, 7)
            return constants.backgroundName(for: p) ?? "\(p)"
        }
        let width = entries.map(\.count).max() ?? 0

        var out = "const uint8_t tile_palette_map[][4] = {\n"
        for (tile, entry) in zip(tiles, entries) {
            let column = (entry + ",").padding(toLength: width + 1, withPad: " ", startingAt: 0)
            let last = entry.padding(toLength: width, withPad: " ", startingAt: 0)
            out += "    { \(column) \(column) \(column) \(last) },  // \(tile.name)\n"
        }
        out += "};\n"
        return out
    }

    /// Background palettes using RGB() macro (from gb/cgb.h).
    /// Always exports exactly 8 palettes, padding with zeros if needed.
    /// Caps at 8 palettes max (GBC hardware limit).
    private static func formatGameBgPalettes(palettes: [GBPalette]) -> String {
        let maxPalettes = 8
        var out = "const uint16_t bg_palettes[\(maxPalettes) * 4] = {\n"
        for i in 0..<maxPalettes {
            if i < palettes.count {
                let palette = palettes[i]
                out += "    // \(palette.name) (\(i))\n"
                out += "    "
                for (ci, color) in palette.colors.enumerated() {
                    out += String(format: "RGB(%-2d, %-2d, %-2d)", color.r, color.g, color.b)
                    if i < maxPalettes - 1 || ci < 3 {
                        out += ", "
                    }
                }
                out += "\n"
            } else {
                out += "    // (unused \(i))\n"
                out += "    "
                for ci in 0..<4 {
                    out += "RGB(0 , 0 , 0 )"
                    if i < maxPalettes - 1 || ci < 3 {
                        out += ", "
                    }
                }
                out += "\n"
            }
        }
        out += "};\n"
        return out
    }

    // MARK: - Spell icon generation

    /// Generate spell_icons.c matching the exact format expected by the game build.
    static func generateSpellIconsC(spellIcons: SpellIconSet) -> String {
        let labels = [
            "Spark icon", "Gaia icon", "Aqua icon", "Tectonic icon",
            "Slide icon", "Dust icon", "1Up mushroom icon",
            "Spark disabled", "Gaia disabled", "Aqua disabled", "Tectonic disabled",
            "Slide disabled", "Dust disabled", "1Up mushroom disabled",
        ]

        var out = "#pragma bank 2\n"
        out += "\n"
        out += "#include <stdint.h>\n"
        out += "\n"
        out += "// 14 tiles x 16 bytes = 224 bytes\n"
        out += "// Order: 7 normal icons, then 7 disabled variants\n"
        out += "//   [0] Spark, [1] Gaia, [2] Aqua, [3] Tectonic, [4] Slide, [5] Dust, [6] 1Up\n"
        out += "//   [7] Spark_DIS, [8] Gaia_DIS, [9] Aqua_DIS, [10] Tectonic_DIS, [11] Slide_DIS, [12] Dust_DIS, [13] 1Up_DIS\n"
        out += "const uint8_t spell_icon_tile_data[] = {\n"

        for (i, icon) in spellIcons.icons.enumerated() {
            out += "    // \(labels[i])\n"
            let bytes = icon.encode()
            // 2 lines of 8 bytes each, formatted as 4 comma-separated pairs
            for row in 0..<2 {
                out += "    "
                for j in 0..<4 {
                    let idx = row * 8 + j * 2
                    out += String(format: "0x%02X,0x%02X", bytes[idx], bytes[idx + 1])
                    if j < 3 {
                        out += ", "
                    } else {
                        out += ","
                    }
                }
                out += "\n"
            }
        }

        out += "};\n"
        return out
    }

    // MARK: - Spell cast tile generation

    /// Generate C array for 32x32 spell cast tiles (7 spells x 16 sub-tiles x 16 bytes = 1792 bytes).
    static func generateSpellCastTilesC(spellCastTiles: SpellCastTileSet) -> String {
        let spellNames = ["Spark", "Gaia", "Aqua", "Tectonic", "Slide", "Dust", "1Up"]

        var out = "// 7 spells x 16 sub-tiles x 16 bytes = 1792 bytes\n"
        out += "// Each spell = 4x4 grid of 8x8 sub-tiles, row-major order\n"
        out += "const uint8_t spell_cast_tile_data[] = {\n"

        for (spellIdx, castTile) in spellCastTiles.tiles.enumerated() {
            out += "    // \(spellNames[spellIdx]) cast — 16 sub-tiles\n"
            for (subIdx, subTile) in castTile.subTiles.enumerated() {
                let row = subIdx / 4
                let col = subIdx % 4
                out += "    // sub-tile [\(row),\(col)]\n"
                let bytes = subTile.encode()
                for line in 0..<2 {
                    out += "    "
                    for j in 0..<4 {
                        let idx = line * 8 + j * 2
                        out += String(format: "0x%02X,0x%02X", bytes[idx], bytes[idx + 1])
                        if j < 3 {
                            out += ", "
                        } else {
                            out += ","
                        }
                    }
                    out += "\n"
                }
            }
        }

        out += "};\n"
        return out
    }

    // MARK: - Indicator tile generation

    /// Generate indicator_tiles.c for 8x8 mini-icons (Emerald, Ruby, Obsidian, Aether).
    static func generateIndicatorTilesC(indicatorTiles: IndicatorTileSet) -> String {
        var out = "#pragma bank 2\n"
        out += "\n"
        out += "#include <stdint.h>\n"
        out += "\n"
        out += "// 4 tiles x 16 bytes = 64 bytes\n"
        out += "// Order: [0] Emerald, [1] Ruby, [2] Obsidian, [3] Aether\n"
        out += "const uint8_t indicator_tile_data[] = {\n"

        for kind in IndicatorKind.allCases {
            let tile = indicatorTiles.tiles[kind.rawValue]
            out += "    // \(kind.name)\n"
            let bytes = tile.encode()
            for row in 0..<2 {
                out += "    "
                for j in 0..<4 {
                    let idx = row * 8 + j * 2
                    out += String(format: "0x%02X,0x%02X", bytes[idx], bytes[idx + 1])
                    if j < 3 {
                        out += ", "
                    } else {
                        out += ","
                    }
                }
                out += "\n"
            }
        }

        out += "};\n"
        out += "\n"
        out += "const uint8_t indicator_tile_palette[] = { "
        out += IndicatorKind.allCases.map { "\($0.paletteIndex)" }.joined(separator: ", ")
        out += " };\n"
        return out
    }

    // MARK: - Text sprite generation

    /// Generate C code for a text sprite, matching chain_sprite_data[] layout.
    /// Layout: all top halves first, then all bottom halves.
    static func generateTextSpriteC(sprite: TextSprite) -> String {
        let tiles = sprite.exportTiles()
        let cols = tiles.count / 2
        let safeName = sprite.name
            .uppercased()
            .replacingOccurrences(of: " ", with: "_")
            .replacingOccurrences(of: "-", with: "_")
            .filter { $0.isLetter || $0.isNumber || $0 == "_" }

        var out = ""
        out += "// Generated by GBSpriteEditor — \"\(sprite.text)\" text sprite\n"
        out += "// 2bpp: color 0=transparent, color 1=white fill, color 3=black outline\n"
        out += "\n"
        out += "#include <stdint.h>\n"
        out += "\n"
        out += "#define TEXT_\(safeName)_COLS \(cols)\n"
        out += "#define TEXT_\(safeName)_TILES \(tiles.count)\n"
        out += "\n"
        out += "const uint8_t text_\(safeName.lowercased())_data[] = {\n"

        out += "    // ============ TOP HALVES (tiles 0-\(cols - 1)) ============\n"
        out += "\n"
        for i in 0..<cols {
            out += "    // col \(i) TOP (tile \(i))\n"
            let bytes = tiles[i].encode()
            // 4 lines of 2 byte-pairs each (lo,hi per row, 2 rows per line)
            for row in stride(from: 0, to: 8, by: 2) {
                out += "    "
                let idx0 = row * 2
                let idx1 = (row + 1) * 2
                out += String(format: "0x%02X,0x%02X, 0x%02X,0x%02X,",
                              bytes[idx0], bytes[idx0 + 1],
                              bytes[idx1], bytes[idx1 + 1])
                out += "\n"
            }
            out += "\n"
        }

        out += "    // ============ BOTTOM HALVES (tiles \(cols)-\(tiles.count - 1)) ============\n"
        out += "\n"
        for i in cols..<tiles.count {
            out += "    // col \(i - cols) BOTTOM (tile \(i))\n"
            let bytes = tiles[i].encode()
            for row in stride(from: 0, to: 8, by: 2) {
                out += "    "
                let idx0 = row * 2
                let idx1 = (row + 1) * 2
                out += String(format: "0x%02X,0x%02X, 0x%02X,0x%02X,",
                              bytes[idx0], bytes[idx0 + 1],
                              bytes[idx1], bytes[idx1 + 1])
                out += "\n"
            }
            out += "\n"
        }

        out += "};\n"
        return out
    }

    /// Legacy inline palette format (for the Export C Code sheet).
    private static func formatPalettesInline(palettes: [GBPalette]) -> String {
        var out = "#define RGB(r,g,b) ((uint16_t)(r) | ((uint16_t)(g) << 5) | ((uint16_t)(b) << 10))\n\n"
        out += "const uint16_t bg_palettes[\(palettes.count) * 4] = {\n"

        for (i, palette) in palettes.enumerated() {
            out += "    // \(palette.name) (\(i))\n"
            out += "    "
            for (ci, color) in palette.colors.enumerated() {
                out += "RGB(\(color.r),\(color.g),\(color.b))"
                if i < palettes.count - 1 || ci < 3 {
                    out += ", "
                }
            }
            out += "\n"
        }

        out += "};\n"
        return out
    }
}
